### ISSUE TITLE
License information in the source code headers is GPL 3+, but it is LGPL 3+ in LICENSE.txt

### ISSUE THREAD

**Issue by jonelo** [lightningj-org/lightningj#17] opened 2018-10-20 09:28 UTC
### Subject of the issue
License information in source code headers is GPL 3+, but it is LGPL 3+ in LICENSE.txt

### Your environment
n/a

### Steps to reproduce
for example, please have a look at the license header of  lightningj/src/main/java/org/lightningj/util/ZBase32.java
```
/************************************************************************
 *                                                                       *
 *  LightningJ                                                           *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU General Public License          *
 *  License as published by the Free Software Foundation; either         *
 *  version 3 of the License, or any later version.                      *
 *                                                                       *
 *  See terms of license at gnu.org.                                     *
 *                                                                       *
 *************************************************************************/
```
There is the statement called

"... under the terms of the GNU General Public License License as published ..."

Note the "License License" in the sentence and there is no "Lesser"

### Expected behaviour

I believe the license should be read as

"... under the terms of the GNU Lesser General Public License as published ..."

because in lightningj/LICENSE.txt

I read that your project has been released under the terms of the LGPL 3+ and not under the terms of the GPL 3+ as the source header suggests.

I haven't cheched all source headers, but spot checks show that there is more than one source affected by this issue.

### Actual behaviour

see the stepts to reproduce

**Comment by herrvendil** [comment] 2018-10-20 11:46
Hi. Yes that I wrong. The license is LGPL v3. I will update the code headers with correct info. Must be a copy’n paste error by me.

Thanks for noticing.
//Philip


20 okt. 2018 kl. 11:28 skrev Johann N. Löfflmann <notifications@github.com<mailto:notifications@github.com>>:

Subject of the issue

License information in source code headers is GPL 3+, but it is LGPL 3+ as in LICENSE.txt

Your environment

n/a

Steps to reproduce

for example, please have a look at the license header of lightningj/src/main/java/org/lightningj/util/ZBase32.java

/************************************************************************
 *                                                                       *
 *  LightningJ                                                           *
 *                                                                       *
 *  This software is free software; you can redistribute it and/or       *
 *  modify it under the terms of the GNU General Public License          *
 *  License as published by the Free Software Foundation; either         *
 *  version 3 of the License, or any later version.                      *
 *                                                                       *
 *  See terms of license at gnu.org<http://gnu.org>.                                     *
 *                                                                       *
 *************************************************************************/


There is the statement called

"... under the terms of the GNU General Public License License as published ..."

Note the "License License" in the sentence.

Expected behaviour

I believe the license should be read as

"... under the terms of the GNU Lesser General Public License as published ..."

because in lightningj/LICENSE.txt

I read that your project has been released under the terms of the LGPL 3+ and not under the terms of the GPL 3+ as the source header suggests.

I haven't cheched all source headers, but spot checks show that there is more than one source affected by this issue.

Actual behaviour

see the stepts to reproduce

**Comment by herrvendil** [comment] 2018-10-20 12:50
Have updated Master with PR #18 clarifying LGPL 3.+

**Comment by herrvendil** [comment] 2018-10-23 06:41
Closing this issue.

**Closed as completed by herrvendil** 2018-10-23 06:41 UTC
